packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@hono/node-server": "^1.19.13"
  "hono": "^4.12.25"
  "uuid": "^11.1.1"
  "@prisma/config>deepmerge-ts": "8.0.2"
  "prisma>mysql2": "3.23.1"

onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"

allowBuilds:
  "@prisma/engines": true
  "prisma": true

minimumReleaseAgeExclude:
  - "@expo/cli@57.0.27"
  - "@expo/router-server@57.0.11"
  - "@expo/ui@57.0.20"
  - babel-preset-expo@57.0.13
  - expo-glass-effect@57.0.4
  - expo-linking@57.0.11
  - expo-modules-core@57.0.19
  - expo-modules-jsi@57.1.1
  - expo-router@57.0.23
  - expo@57.0.25
